SCRIP_METADATA = {
    "RELIANCE": {"sector": "Energy", "lot_size": 1, "tick_size": 0.05},
    "TCS": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
    "HDFCBANK": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "INFY": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
    "ICICIBANK": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "HINDUNILVR": {"sector": "FMCG", "lot_size": 1, "tick_size": 0.05},
    "SBIN": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "BHARTIARTL": {"sector": "Telecom", "lot_size": 1, "tick_size": 0.05},
    "KOTAKBANK": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "ITC": {"sector": "FMCG", "lot_size": 1, "tick_size": 0.05},
    "LT": {"sector": "Construction", "lot_size": 1, "tick_size": 0.05},
    "BAJFINANCE": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "AXISBANK": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "ASIANPAINT": {"sector": "Consumer Durables", "lot_size": 1, "tick_size": 0.05},
    "MARUTI": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "SUNPHARMA": {"sector": "Healthcare", "lot_size": 1, "tick_size": 0.05},
    "TITAN": {"sector": "Consumer Durables", "lot_size": 1, "tick_size": 0.05},
    "ULTRACEMCO": {"sector": "Construction Materials", "lot_size": 1, "tick_size": 0.05},
    "TATASTEEL": {"sector": "Metals", "lot_size": 1, "tick_size": 0.05},
    "HCLTECH": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
    "ADANIENT": {"sector": "Metals & Mining", "lot_size": 1, "tick_size": 0.05},
    "NTPC": {"sector": "Power", "lot_size": 1, "tick_size": 0.05},
    "POWERGRID": {"sector": "Power", "lot_size": 1, "tick_size": 0.05},
    "M&M": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "TATAMOTORS": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "BAJAJFINSV": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "WIPRO": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
    "NESTLEIND": {"sector": "FMCG", "lot_size": 1, "tick_size": 0.05},
    "ONGC": {"sector": "Oil & Gas", "lot_size": 1, "tick_size": 0.05},
    "GRASIM": {"sector": "Construction Materials", "lot_size": 1, "tick_size": 0.05},
    "JSWSTEEL": {"sector": "Metals", "lot_size": 1, "tick_size": 0.05},
    "TECHM": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
    "HINDALCO": {"sector": "Metals", "lot_size": 1, "tick_size": 0.05},
    "COALINDIA": {"sector": "Metals & Mining", "lot_size": 1, "tick_size": 0.05},
    "INDUSINDBK": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "DRREDDY": {"sector": "Healthcare", "lot_size": 1, "tick_size": 0.05},
    "CIPLA": {"sector": "Healthcare", "lot_size": 1, "tick_size": 0.05},
    "EICHERMOT": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "SBILIFE": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "DIVISLAB": {"sector": "Healthcare", "lot_size": 1, "tick_size": 0.05},
    "TATACONSUM": {"sector": "FMCG", "lot_size": 1, "tick_size": 0.05},
    "BAJAJ-AUTO": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "APOLLOHOSP": {"sector": "Healthcare", "lot_size": 1, "tick_size": 0.05},
    "UPL": {"sector": "Chemicals", "lot_size": 1, "tick_size": 0.05},
    "BRITANNIA": {"sector": "FMCG", "lot_size": 1, "tick_size": 0.05},
    "HEROMOTOCO": {"sector": "Automobile", "lot_size": 1, "tick_size": 0.05},
    "BPCL": {"sector": "Oil & Gas", "lot_size": 1, "tick_size": 0.05},
    "ADANIPORTS": {"sector": "Services", "lot_size": 1, "tick_size": 0.05},
    "HDFCLIFE": {"sector": "Financial Services", "lot_size": 1, "tick_size": 0.05},
    "LTIM": {"sector": "IT", "lot_size": 1, "tick_size": 0.05},
}
